# Generated by Django 4.1.12 on 2024-02-09 05:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=225, unique=True)),
                ('user_mobile_number', models.CharField(max_length=225, unique=True)),
                ('user_password', models.CharField(max_length=225)),
                ('is_verify', models.BooleanField(default=False)),
                ('user_role', models.CharField(max_length=225)),
                ('otp_key', models.CharField(max_length=225)),
            ],
        ),
    ]
