# Generated by Django 4.1.12 on 2024-02-07 06:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_mobile_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('2ac39253-262a-410a-86ec-99808b541e87'), editable=False, primary_key=True, serialize=False),
        ),
    ]
