# Generated by Django 4.1.12 on 2024-03-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_mobile_number',
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
