# Generated by Django 4.1.12 on 2024-02-21 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_user_name'),
        ('user', '0002_alter_user_user_name_alter_user_user_role'),
    ]

    operations = [
    ]
