# Generated by Django 5.0.1 on 2024-02-08 05:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_user_mobile_number_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.EmailField(max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('5f5d6031-1311-45c0-9d53-e695d5dd6f27'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_mobile_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
