# Generated by Django 4.1.13 on 2024-02-08 06:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_user_email_alter_user_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('2f5ffb95-10f0-4b43-ae92-e36b265102eb'), editable=False, primary_key=True, serialize=False),
        ),
    ]
