# Generated by Django 4.1.12 on 2024-02-26 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_merge_20240221_2225'),
        ('user', '0003_merge_20240222_1101'),
    ]

    operations = [
    ]
