# Generated by Django 4.1.13 on 2024-02-08 06:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('b9cc0cf7-044c-4cd5-9f93-1161c037731d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
