# Generated by Django 4.1.13 on 2024-02-08 06:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('ad9e7589-8f19-484a-8459-04668f38586b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
