# Generated by Django 4.1.13 on 2024-02-08 06:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('322f0a3d-d403-4d8b-8bff-32c5fb72a1ed'), editable=False, primary_key=True, serialize=False),
        ),
    ]
