# Generated by Django 4.1.13 on 2024-02-08 06:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('70c25b11-807c-4bb5-a36b-7fdb9f802d42'), editable=False, primary_key=True, serialize=False),
        ),
    ]
