# Generated by Django 4.1.13 on 2024-02-08 06:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('aa792e2d-de27-46aa-a654-21543c79f679'), editable=False, primary_key=True, serialize=False),
        ),
    ]
