# Generated by Django 4.1.13 on 2024-02-08 06:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('9177834a-5585-4090-a63d-d3c39e313c2a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
