# Generated by Django 4.1.13 on 2024-02-08 07:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('e9f470c9-1a9d-468a-a9f6-36830d902fc4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
