# Generated by Django 4.1.12 on 2024-02-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default=None, upload_to='brand/'),
        ),
    ]
