# Generated by Django 4.1.12 on 2024-02-21 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_status',
            new_name='is_active',
        ),
    ]
