# Generated by Django 4.1.12 on 2024-02-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_rename_category_status_category_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
