# Generated by Django 4.1.12 on 2024-03-13 06:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0002_alter_brand_brand_name'),
        ('category', '0002_alter_category_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('country_of_origin', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer', models.CharField(max_length=255)),
                ('special_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dimensions', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=10), size=3)),
                ('color', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('style_design', models.CharField(max_length=100)),
                ('surface_finish', models.CharField(max_length=100)),
                ('edge_type', models.CharField(max_length=100)),
                ('stock_quantity', models.PositiveIntegerField()),
                ('availability', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('demo_video', models.URLField()),
                ('shipping_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_dimensions', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=10), size=3)),
                ('special_shipping_notes', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
                ('technical_specifications', models.TextField()),
                ('installation_instructions', models.TextField()),
                ('maintenance_instructions', models.TextField()),
                ('warranty_information', models.TextField()),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax_code', models.CharField(max_length=20)),
                ('tax_exempt', models.BooleanField(default=False)),
                ('size_variant', models.CharField(max_length=100)),
                ('color_variant', models.CharField(max_length=100)),
                ('style_variant', models.CharField(max_length=100)),
                ('bulk_quantity_pricing', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_order_quantity', models.PositiveIntegerField()),
                ('sales_start_date', models.DateTimeField()),
                ('sales_end_date', models.DateTimeField()),
                ('customization_choices', models.TextField()),
                ('customization_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('num_reviews', models.PositiveIntegerField()),
                ('return_period_days', models.PositiveIntegerField()),
                ('return_conditions', models.TextField()),
                ('sales_quantity', models.PositiveIntegerField()),
                ('sales_revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_discontinued', models.BooleanField(default=False)),
                ('admin_notes', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user_assigned', models.CharField(max_length=100)),
                ('approval_status', models.CharField(max_length=20)),
                ('internal_product_id', models.CharField(max_length=50)),
                ('sales_representative', models.CharField(max_length=100)),
                ('product_url', models.URLField()),
                ('notification_preferences', models.TextField()),
                ('audit_trail', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.brand')),
                ('related_products', models.ManyToManyField(to='product.product')),
            ],
        ),
    ]
