# Generated by Django 4.1.12 on 2024-03-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='maintainance_details',
            new_name='maintenance_details',
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='SIV40595', max_length=8),
        ),
    ]
