# Generated by Django 4.1.12 on 2024-03-13 17:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_color_alter_product_dimensions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='related_products',
        ),
        migrations.AlterField(
            model_name='product',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='approval_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='audit_trail',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='bulk_quantity_pricing',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_variant',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='customization_choices',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='customization_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='demo_video',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='installation_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='internal_product_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='maintenance_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_order_quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='notification_preferences',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='num_reviews',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='return_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='return_period_days',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_end_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_representative',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_revenue',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_start_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_dimensions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=10), null=True, size=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_variant',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='special_shipping_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='style_variant',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='technical_specifications',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='user_assigned',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty_information',
            field=models.TextField(blank=True),
        ),
    ]
