# Generated by Django 4.1.12 on 2024-03-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_maintainance_details_product_maintenance_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock_quantity',
            new_name='maximum_stock_level',
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_stock_level',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='JOB10753', max_length=8),
        ),
    ]
