# Generated by Django 4.1.12 on 2024-03-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_stock_quantity_product_maximum_stock_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tax_code',
            new_name='hsn_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tax_class',
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='OTC46194', max_length=8),
        ),
    ]
