# Generated by Django 4.1.12 on 2024-03-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_related_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sales_end_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_start_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
