# Generated by Django 4.1.12 on 2024-04-13 08:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=225)),
                ('mobile_number', models.CharField(max_length=225, unique=True)),
                ('pincode', models.CharField(blank=True, max_length=225)),
                ('locality', models.CharField(blank=True, max_length=225)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=225)),
                ('state', models.CharField(blank=True, max_length=225)),
                ('landmark', models.CharField(blank=True, max_length=225)),
                ('alternate_mobile_number', models.CharField(blank=True, max_length=225)),
            ],
        ),
    ]
