# Generated by Django 4.1.12 on 2024-03-07 10:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '__first__'),
        ('dealer', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=225)),
                ('brand_logo', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('dealer', models.ManyToManyField(to='dealer.dealer')),
            ],
        ),
    ]
