# Generated by Django 4.1.12 on 2024-02-26 05:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '__first__'),
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='brand_status',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='brand',
            name='dealer',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='dealer.dealer'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_logo',
            field=models.TextField(blank=True),
        ),
    ]
