# Generated by Django 4.1.12 on 2024-02-09 09:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('manager_name', models.CharField(max_length=225)),
                ('manager_email', models.EmailField(max_length=225, unique=True)),
                ('manager_mobile_number', models.CharField(max_length=10, unique=True)),
                ('manager_address', models.TextField(blank=True)),
            ],
        ),
    ]
