# Generated by Django 5.0.1 on 2024-02-08 05:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager_id', models.UUIDField(default=uuid.UUID('ea1c8d1a-8218-404b-bfe8-1095f3598dbf'), editable=False, primary_key=True, serialize=False)),
                ('manager_name', models.CharField(max_length=225)),
                ('manager_email', models.EmailField(max_length=225, unique=True)),
                ('manager_mobile_number', models.CharField(max_length=10, unique=True)),
                ('manager_address', models.TextField(blank=True)),
            ],
        ),
    ]
