# Generated by Django 4.1.13 on 2024-02-08 06:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='manager_id',
            field=models.UUIDField(default=uuid.UUID('54795dc2-4169-465e-a80e-d6c76afa8dd8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
