# Generated by Django 4.1.13 on 2024-02-08 06:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_manager_manager_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='manager_id',
            field=models.UUIDField(default=uuid.UUID('f90e370f-2f9e-4d2f-aaf2-9f9966d68de8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
