# Generated by Django 4.1.13 on 2024-02-08 06:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_manager_manager_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='manager_id',
            field=models.UUIDField(default=uuid.UUID('87149794-24c1-4f28-a0e7-83d8bc107842'), editable=False, primary_key=True, serialize=False),
        ),
    ]
