# Generated by Django 4.1.13 on 2024-02-08 06:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_manager_manager_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='manager_id',
            field=models.UUIDField(default=uuid.UUID('215c0394-8fb5-4426-98ed-96d7556bb455'), editable=False, primary_key=True, serialize=False),
        ),
    ]
