# Generated by Django 4.1.13 on 2024-02-08 06:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_manager_manager_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='manager_id',
            field=models.UUIDField(default=uuid.UUID('e297e536-831f-498d-91ca-6ca7595444f3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
