# Generated by Django 4.1.13 on 2024-02-08 06:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_alter_manager_manager_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='manager_id',
            field=models.UUIDField(default=uuid.UUID('1ec54311-3c1e-4a0a-b634-f81fc02a8582'), editable=False, primary_key=True, serialize=False),
        ),
    ]
