# Generated by Django 4.1.13 on 2024-02-08 06:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_alter_manager_manager_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='manager_id',
            field=models.UUIDField(default=uuid.UUID('ceb6a05e-8ebf-47fc-b526-d32ff7c880b6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
