# Generated by Django 4.1.13 on 2024-02-08 07:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_alter_manager_manager_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='manager_id',
            field=models.UUIDField(default=uuid.UUID('1a370e66-b53d-4f7e-a5e5-14a1b6e4d156'), editable=False, primary_key=True, serialize=False),
        ),
    ]
