# Generated by Django 4.1.12 on 2024-03-16 17:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('dealer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dealer_name', models.CharField(max_length=225)),
                ('is_active', models.BooleanField(default=True)),
                ('dealer_email', models.EmailField(max_length=225, unique=True)),
                ('dealer_mobile_number', models.CharField(max_length=10, unique=True)),
                ('dealer_address', models.TextField(blank=True)),
                ('dealer_landmark', models.TextField(blank=True)),
                ('dealer_image', models.TextField(blank=True)),
                ('dealer_description', models.TextField(blank=True)),
            ],
        ),
    ]
