# Generated by Django 4.1.12 on 2024-03-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='dealer_landmark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
