# Generated by Django 4.1.12 on 2024-03-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='dealer_email',
            field=models.EmailField(max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='dealer_mobile_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
