# Generated by Django 4.1.12 on 2024-02-21 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0002_dealer_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='brand',
        ),
    ]
