# Generated by Django 4.1.12 on 2024-02-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0003_remove_dealer_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='dealer_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='dealer_image',
            field=models.ImageField(blank=True, upload_to='dealer/'),
        ),
    ]
