# Generated by Django 4.1.12 on 2024-02-23 05:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0004_dealer_dealer_description_dealer_dealer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='dealer_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
