# Generated by Django 4.1.12 on 2024-03-27 06:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0005_alter_product_sku_alter_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductHighlight',
            fields=[
                ('product_highlight_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('flash_deal', models.BooleanField(default=False)),
                ('discount_date', models.DateField()),
                ('hot_deals', models.BooleanField(default=False)),
                ('new', models.BooleanField(default=False)),
                ('sale', models.BooleanField(default=False)),
                ('best_seller', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('top_rated', models.BooleanField(default=False)),
                ('big_saving', models.BooleanField(default=False)),
                ('trending', models.BooleanField(default=False)),
                ('product', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
