# Generated by Django 4.1.12 on 2024-03-27 11:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product_highlight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthighlight',
            name='discount_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='producthighlight',
            name='product_highlight_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
