# Generated by Django 4.1.12 on 2024-03-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_highlight', '0002_alter_producthighlight_discount_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthighlight',
            name='flash_deal',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
