# Generated by Django 4.1.12 on 2024-03-28 05:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_sku'),
        ('product_highlight', '0003_alter_producthighlight_flash_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthighlight',
            name='product',
            field=models.OneToOneField(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
