# Generated by Django 4.1.12 on 2024-03-29 09:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '__first__'),
        ('product', '0007_alter_product_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('current_stock', models.PositiveBigIntegerField(blank=True, null=True)),
                ('unit', models.PositiveBigIntegerField(blank=True, null=True)),
                ('default_price', models.FloatField(blank=True, null=True)),
                ('regular_selling_price', models.FloatField(blank=True, null=True)),
                ('regular_buying_price', models.FloatField(blank=True, null=True)),
                ('mrp', models.FloatField(blank=True, null=True)),
                ('stock_status', models.BooleanField(default=False)),
                ('category_id', models.ForeignKey(default=uuid.uuid4, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('product_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
